export const GET_PR_TRACKER = 'GET_PR_TRACKER';
export const SET_PR_TRACKER_REFRESH_LOADING = 'SET_PR_TRACKER_REFRESH_LOADING';
export const SET_PR_TRACKER_LOADING = 'SET_PR_TRACKER_LOADING';
export const SET_FILTERS = 'SET_FILTERS';
